# -*- coding: utf-8 -*-
"""MachineLearning

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y58TR_zEbPacX-1LauRWIYcv1DTZQ2D1
"""

!pip install scikit-learn

#import library yang diperlukan
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import pandas as pd
import numpy as np
from scipy import stats

sales = pd.Series([200000, 150000, 100000, 50000, 0, -50000])
ads_spend = pd.Series([8000, 12000, 16000, 20000, 24000, 28000])
sales

ads_spend

X = ads_spend.values.reshape(-1, 1)
y = sales.values.reshape(-1, 1)
model = LinearRegression()
model.fit(X, y)

predicted_sales = model.predict(X)
predicted_sales

mse = mean_squared_error(y, predicted_sales)
r2 = r2_score(y, predicted_sales)

print(f'Mean Squared Error (MSE) : {mse:.2f}')
print(f'R-Squared (Coefficient of Determination) : {r2:.2f}')

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10,8))
plt.scatter(X, y, color='red', label = 'Actual Sales')
plt.plot(X, predicted_sales, color = 'blue', label='Predicted Sales')
plt.xlabel('Advertising Spend')
plt.ylabel('Sales')
plt.title('Sales vs Advertising')
plt.legend()
plt.show()

# Install matplotlib Searborn
!pip install matplotlib seaborn